package main

import (
	"context"
	"fmt"
	"log"
	"slices"
	"strings"
	"sync/atomic"

	jira "github.com/andygrunwald/go-jira/v2/cloud"
)

const (
	aiGeneratedLabel = "ai-generated"
	aiBodyMarker     = "This ticket was generated by AI."
)

type jiraFacade interface {
	findIncomingTickets(project string, teamMembers []string, processedLabel string) ([]jira.Issue, error)
	reassign(issueKey, accountID string) error
	addComment(issueKey, body string) error
	addLabel(issue *jira.Issue, label string) error
}

type evaluatorFacade interface {
	Evaluate(ctx context.Context, summary, description string) (EvalResult, error)
}

type Agent struct {
	cfg       Config
	jira      jiraFacade
	evaluator evaluatorFacade
	rrIndex   atomic.Uint32
}

func newAgent(cfg Config, jiraClient *JiraClient, evaluator *Evaluator) *Agent {
	return &Agent{cfg: cfg, jira: jiraClient, evaluator: evaluator}
}

func (a *Agent) run() error {
	issues, err := a.jira.findIncomingTickets(a.cfg.JiraProject, a.cfg.TeamMembers, a.cfg.ProcessedLabel)
	if err != nil {
		return fmt.Errorf("fetching triage tickets: %w", err)
	}

	log.Printf("Found %d ticket(s) to process", len(issues))

	for i := range issues {
		if err := a.process(context.Background(), &issues[i]); err != nil {
			log.Printf("Error processing %s: %v", issues[i].Key, err)
		}
	}
	return nil
}

func (a *Agent) process(ctx context.Context, issue *jira.Issue) error {
	if !isAIGenerated(issue) {
		return a.handleValid(issue)
	}

	result, err := a.evaluator.Evaluate(ctx, issue.Fields.Summary, issue.Fields.Description)
	if err != nil {
		return fmt.Errorf("evaluating %s: %w", issue.Key, err)
	}

	log.Printf("%s: verdict=%s jenkins=%v server=%v scope=%s",
		issue.Key, result.Verdict, result.JenkinsLinkFound, result.ServerNameFound, result.Scope)

	if result.Verdict == VerdictSpam {
		return a.handleSpam(issue, result.Comment)
	}
	return a.handleValid(issue)
}

// isAIGenerated returns true when both signals are present, indicating the
// ticket was created by the QA AI agent and needs evaluation.
func isAIGenerated(issue *jira.Issue) bool {
	return hasLabel(issue, aiGeneratedLabel) &&
		strings.Contains(issue.Fields.Description, aiBodyMarker)
}

func (a *Agent) handleSpam(issue *jira.Issue, comment string) error {
	log.Printf("%s: returning to reporter — %s", issue.Key, comment)

	if issue.Fields.Reporter == nil {
		log.Printf("%s: no reporter found, skipping reassignment", issue.Key)
		return a.jira.addLabel(issue, a.cfg.ProcessedLabel)
	}

	if err := a.jira.reassign(issue.Key, issue.Fields.Reporter.AccountID); err != nil {
		return err
	}
	if err := a.jira.addComment(issue.Key, comment); err != nil {
		return err
	}
	return a.jira.addLabel(issue, a.cfg.ProcessedLabel)
}

func (a *Agent) handleValid(issue *jira.Issue) error {
	assignee := a.nextMember()
	log.Printf("%s: valid — assigning to %s", issue.Key, assignee)

	if err := a.jira.reassign(issue.Key, assignee); err != nil {
		return err
	}
	return a.jira.addLabel(issue, a.cfg.ProcessedLabel)
}

func (a *Agent) nextMember() string {
	idx := a.rrIndex.Add(1) - 1
	return a.cfg.TeamMembers[int(idx)%len(a.cfg.TeamMembers)]
}

func hasLabel(issue *jira.Issue, label string) bool {
	return slices.Contains(issue.Fields.Labels, label)
}
