package main

import (
	"context"
	"fmt"
	"log"
	"slices"
	"strings"
	"sync/atomic"

	jira "github.com/andygrunwald/go-jira/v2/cloud"
)

const (
	aiGeneratedLabel = "ai-generated"
	aiBodyMarker     = "This ticket was generated by AI."
)

type Agent struct {
	cfg       Config
	jira      *JiraClient
	evaluator *Evaluator
	rrIndex   atomic.Uint32
}

func newAgent(cfg Config, jiraClient *JiraClient, evaluator *Evaluator) *Agent {
	return &Agent{cfg: cfg, jira: jiraClient, evaluator: evaluator}
}

func (a *Agent) run() error {
	issues, err := a.jira.findIncomingTickets(a.cfg.JiraProject, a.cfg.TeamMembers, a.cfg.ProcessedLabel)
	if err != nil {
		return fmt.Errorf("fetching triage tickets: %w", err)
	}

	log.Printf("Found %d ticket(s) to process", len(issues))

	for i := range issues {
		if err := a.process(context.Background(), &issues[i]); err != nil {
			log.Printf("Error processing %s: %v", issues[i].Key, err)
		}
	}
	return nil
}

func (a *Agent) process(ctx context.Context, issue *jira.Issue) error {
	if !isAIGenerated(issue) {
		// Not AI-generated — route to team without evaluation.
		return a.handleValid(issue, "not AI-generated")
	}

	verdict, reason, err := a.evaluator.Evaluate(ctx, issue.Fields.Summary, issue.Fields.Description)
	if err != nil {
		return fmt.Errorf("evaluating %s: %w", issue.Key, err)
	}

	log.Printf("%s: verdict=%s reason=%q", issue.Key, verdict, reason)

	if verdict == VerdictSpam {
		return a.handleSpam(issue, reason)
	}
	return a.handleValid(issue, reason)
}

// isAIGenerated returns true when the ticket carries the known AI-generation
// signals — label and body marker — indicating it needs evaluation.
func isAIGenerated(issue *jira.Issue) bool {
	return hasLabel(issue, aiGeneratedLabel) &&
		strings.Contains(issue.Fields.Description, aiBodyMarker)
}

func (a *Agent) handleSpam(issue *jira.Issue, reason string) error {
	log.Printf("%s: spam — reassigning to reporter", issue.Key)

	if issue.Fields.Reporter == nil {
		log.Printf("%s: no reporter, skipping reassignment", issue.Key)
		return a.jira.addLabel(issue, a.cfg.ProcessedLabel)
	}

	comment := fmt.Sprintf(
		"This ticket was automatically reviewed and determined to be insufficiently validated.\n\n"+
			"Reason: %s\n\n"+
			"It has been reassigned to the original reporter for review before being actioned by the team.",
		reason,
	)

	if err := a.jira.reassign(issue.Key, issue.Fields.Reporter.AccountID); err != nil {
		return err
	}
	if err := a.jira.addComment(issue.Key, comment); err != nil {
		return err
	}
	return a.jira.addLabel(issue, a.cfg.ProcessedLabel)
}

func (a *Agent) handleValid(issue *jira.Issue, reason string) error {
	assignee := a.nextMember()
	log.Printf("%s: valid — assigning to %s (%s)", issue.Key, assignee, reason)

	if err := a.jira.reassign(issue.Key, assignee); err != nil {
		return err
	}
	return a.jira.addLabel(issue, a.cfg.ProcessedLabel)
}

func (a *Agent) nextMember() string {
	idx := a.rrIndex.Add(1) - 1
	return a.cfg.TeamMembers[int(idx)%len(a.cfg.TeamMembers)]
}

func hasLabel(issue *jira.Issue, label string) bool {
	return slices.Contains(issue.Fields.Labels, label)
}
