apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jira-k8s-agent-external-secret
  namespace: jira-k8s-agent
  labels:
    app: jira-k8s-agent
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: jira-k8s-agent-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: jira-url  # pragma: allowlist secret
    remoteRef:
      key: jira-k8s-agent
      property: jira-url
  - secretKey: jira-email  # pragma: allowlist secret
    remoteRef:
      key: jira-k8s-agent
      property: jira-email
  - secretKey: jira-api-token  # pragma: allowlist secret
    remoteRef:
      key: jira-k8s-agent
      property: jira-api-token
  - secretKey: huggingface-token  # pragma: allowlist secret
    remoteRef:
      key: jira-k8s-agent
      property: huggingface-token
  - secretKey: jenkins-username  # pragma: allowlist secret
    remoteRef:
      key: jira-k8s-agent
      property: jenkins-username
  - secretKey: jenkins-api-token  # pragma: allowlist secret
    remoteRef:
      key: jira-k8s-agent
      property: jenkins-api-token
  - secretKey: langchain-api-key  # pragma: allowlist secret
    remoteRef:
      key: jira-k8s-agent
      property: langchain-api-key
