apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfigs-external-secret
  namespace: jira-k8s-agent
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cluster-kubeconfigs
    creationPolicy: Owner
  data:
  - secretKey: hldc02  # pragma: allowlist secret
    remoteRef:
      key: internal/jira-k8s-agent
      property: kubeconfig-hldc02
  - secretKey: hldc03  # pragma: allowlist secret
    remoteRef:
      key: internal/jira-k8s-agent
      property: kubeconfig-hldc03
