apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jira-triage-agent-external-secret
  namespace: jira-k8s-agent
  labels:
    app: jira-triage-agent
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: jira-triage-agent-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: jira-url  # pragma: allowlist secret
    remoteRef:
      key: jira-triage-agent
      property: jira-url
  - secretKey: jira-pat  # pragma: allowlist secret
    remoteRef:
      key: jira-triage-agent
      property: jira-pat
  - secretKey: huggingface-token  # pragma: allowlist secret
    remoteRef:
      key: jira-triage-agent
      property: huggingface-token
  - secretKey: langchain-api-key  # pragma: allowlist secret
    remoteRef:
      key: jira-triage-agent
      property: langchain-api-key
