apiVersion: v1
kind: Service
metadata:
  name: jira-agent
  namespace: jira-k8s-agent
  labels:
    app: jira-agent
spec:
  selector:
    app: jira-agent
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
